!!python/object:ml_collections.config_dict.config_dict.FrozenConfigDict
_configdict: !!python/object:ml_collections.config_dict.config_dict.ConfigDict
  _convert_dict: true
  _fields:
    ckpt_root: output_shift/echonet_dynamic_uncond_MoE6_greyscale_uvit_mid_4by4_Y_bound/ckpts
    dataset: &id001 !!python/object:ml_collections.config_dict.config_dict.ConfigDict
      _convert_dict: true
      _fields:
        SNR_scale: 4.0
        Y_bound:
        - 512.0
        Y_entropy:
        - 5.419
        - 2.769
        - 2.659
        - 1.88
        - 2.022
        - 1.575
        - 1.018
        - 1.338
        - 1.593
        - 1.484
        - 1.309
        - 1.163
        - 0.928
        - 0.925
        - 1.051
        - 0.852
        Y_max:
        - 148.0
        - 107.812
        - 89.625
        - 47.0
        - 56.938
        - 34.0
        - 14.758
        - 29.281
        - 38.125
        - 35.156
        - 27.938
        - 22.0
        - 12.641
        - 12.125
        - 18.391
        - 11.641
        Y_mean:
        - -390.081
        - 0.103
        - -0.947
        - 0.171
        - 0.192
        - 0.203
        - 0.001
        - 0.061
        - 0.233
        - -0.075
        - -0.051
        - -0.199
        - -0.046
        - -0.076
        - -0.042
        - 0.029
        Y_min:
        - -512.0
        - -108.688
        - -112.5
        - -52.5
        - -55.75
        - -36.75
        - -14.586
        - -27.062
        - -37.156
        - -36.156
        - -28.484
        - -27.75
        - -13.672
        - -14.266
        - -19.562
        - -10.367
        Y_std:
        - 163.706
        - 28.348
        - 26.485
        - 11.872
        - 13.871
        - 8.085
        - 2.919
        - 6.039
        - 8.605
        - 7.49
        - 5.683
        - 4.875
        - 2.372
        - 2.172
        - 3.337
        - 1.668
        block_sz: 4
        cache: true
        cache_name: cached_echonet_dynamic_4by4_4Y
        dataset_type: dynamic
        greyscale: true
        low_freqs: 12
        name: echonet
        path: data/scratch/datasets/EchoNet-Dynamic
        resolution: 112
        reweight: true
        reweight_dim: 1
        temperature: 0.0
        tokens: 196
      _locked: false
      _type_safe: true
    eval: &id002 !!python/object:ml_collections.config_dict.config_dict.ConfigDict
      _convert_dict: true
      _fields:
        cleanup_samples: true
        eval_start: 110000
        is_batch_size: 32
        lpips_batch_size: 32
        mini_batch_size: 500
        n_samples: 50000
        sample_steps: 100
      _locked: false
      _type_safe: true
    eval_dir: output/evaluation/echonet_uncond_4by4_low16_new
    lr_scheduler: &id003 !!python/object:ml_collections.config_dict.config_dict.ConfigDict
      _convert_dict: true
      _fields:
        name: customized
        warmup_steps: 5000
      _locked: false
      _type_safe: true
    mixed_precision: 'no'
    name: echonet_dynamic_uncond_uvit_greyscale_mid_4by4
    nnet: &id004 !!python/object:ml_collections.config_dict.config_dict.ConfigDict
      _convert_dict: true
      _fields:
        MoE: &id005 !!python/object:ml_collections.config_dict.config_dict.ConfigDict
          _convert_dict: true
          _fields:
            aux_loss_alpha: 0.001
            depth: 1
            noise_eps: 0.01
            num_experts: 6
            router: topk
            top_k: 2
            type: normal
          _locked: false
          _type_safe: true
        depth: 16
        embed_dim: 768
        low_freqs: 12
        mlp_ratio: 4
        mlp_time_embed: true
        name: uvit_greyscale_moe
        num_classes: -1
        num_heads: 12
        qkv_bias: false
        tokens: 196
        use_moe: true
      _locked: false
      _type_safe: true
    optimizer: &id006 !!python/object:ml_collections.config_dict.config_dict.ConfigDict
      _convert_dict: true
      _fields:
        betas: &id007 !!python/tuple
        - 0.99
        - 0.99
        lr: 0.0002
        name: adamw
        weight_decay: 0.03
      _locked: false
      _type_safe: true
    pred: noise_pred
    private: &id008 !!python/object:ml_collections.config_dict.config_dict.ConfigDict
      _convert_dict: true
      _fields:
        accountant: prv
        dp_method: dpsgd
        max_grad_norm: 1.0
        noise_multiplier: 0.5
        secure_mode: false
        target_delta: 1.0e-05
        target_epsilon: 10
        use_dp: false
      _locked: false
      _type_safe: true
    sample: &id009 !!python/object:ml_collections.config_dict.config_dict.ConfigDict
      _convert_dict: true
      _fields:
        algorithm: euler_maruyama_ode
        mini_batch_size: 500
        n_samples: 50000
        path: data/scratch/samples
        sample_steps: 100
        save_npz: ''
        save_start: 10000
      _locked: false
      _type_safe: true
    sample_dir: output_shift/echonet_dynamic_uncond_MoE6_greyscale_uvit_mid_4by4_Y_bound/samples
    seed: 1234
    train: &id010 !!python/object:ml_collections.config_dict.config_dict.ConfigDict
      _convert_dict: true
      _fields:
        batch_size: 512
        eval_interval: 25000
        log_interval: 100
        mode: uncond
        n_steps: 500000
        save_interval: 25000
      _locked: false
      _type_safe: true
    workdir: output_shift/echonet_dynamic_uncond_MoE6_greyscale_uvit_mid_4by4_Y_bound
  _locked: false
  _type_safe: true
_convert_dict: true
_fields:
  ckpt_root: output_shift/echonet_dynamic_uncond_MoE6_greyscale_uvit_mid_4by4_Y_bound/ckpts
  dataset: !!python/object:ml_collections.config_dict.config_dict.FrozenConfigDict
    _configdict: *id001
    _convert_dict: true
    _fields:
      SNR_scale: 4.0
      Y_bound: !!python/tuple
      - 512.0
      Y_entropy: !!python/tuple
      - 5.419
      - 2.769
      - 2.659
      - 1.88
      - 2.022
      - 1.575
      - 1.018
      - 1.338
      - 1.593
      - 1.484
      - 1.309
      - 1.163
      - 0.928
      - 0.925
      - 1.051
      - 0.852
      Y_max: !!python/tuple
      - 148.0
      - 107.812
      - 89.625
      - 47.0
      - 56.938
      - 34.0
      - 14.758
      - 29.281
      - 38.125
      - 35.156
      - 27.938
      - 22.0
      - 12.641
      - 12.125
      - 18.391
      - 11.641
      Y_mean: !!python/tuple
      - -390.081
      - 0.103
      - -0.947
      - 0.171
      - 0.192
      - 0.203
      - 0.001
      - 0.061
      - 0.233
      - -0.075
      - -0.051
      - -0.199
      - -0.046
      - -0.076
      - -0.042
      - 0.029
      Y_min: !!python/tuple
      - -512.0
      - -108.688
      - -112.5
      - -52.5
      - -55.75
      - -36.75
      - -14.586
      - -27.062
      - -37.156
      - -36.156
      - -28.484
      - -27.75
      - -13.672
      - -14.266
      - -19.562
      - -10.367
      Y_std: !!python/tuple
      - 163.706
      - 28.348
      - 26.485
      - 11.872
      - 13.871
      - 8.085
      - 2.919
      - 6.039
      - 8.605
      - 7.49
      - 5.683
      - 4.875
      - 2.372
      - 2.172
      - 3.337
      - 1.668
      block_sz: 4
      cache: true
      cache_name: cached_echonet_dynamic_4by4_4Y
      dataset_type: dynamic
      greyscale: true
      low_freqs: 12
      name: echonet
      path: data/scratch/datasets/EchoNet-Dynamic
      resolution: 112
      reweight: true
      reweight_dim: 1
      temperature: 0.0
      tokens: 196
    _locked: false
    _type_safe: true
  eval: !!python/object:ml_collections.config_dict.config_dict.FrozenConfigDict
    _configdict: *id002
    _convert_dict: true
    _fields:
      cleanup_samples: true
      eval_start: 110000
      is_batch_size: 32
      lpips_batch_size: 32
      mini_batch_size: 500
      n_samples: 50000
      sample_steps: 100
    _locked: false
    _type_safe: true
  eval_dir: output/evaluation/echonet_uncond_4by4_low16_new
  lr_scheduler: !!python/object:ml_collections.config_dict.config_dict.FrozenConfigDict
    _configdict: *id003
    _convert_dict: true
    _fields:
      name: customized
      warmup_steps: 5000
    _locked: false
    _type_safe: true
  mixed_precision: 'no'
  name: echonet_dynamic_uncond_uvit_greyscale_mid_4by4
  nnet: !!python/object:ml_collections.config_dict.config_dict.FrozenConfigDict
    _configdict: *id004
    _convert_dict: true
    _fields:
      MoE: !!python/object:ml_collections.config_dict.config_dict.FrozenConfigDict
        _configdict: *id005
        _convert_dict: true
        _fields:
          aux_loss_alpha: 0.001
          depth: 1
          noise_eps: 0.01
          num_experts: 6
          router: topk
          top_k: 2
          type: normal
        _locked: false
        _type_safe: true
      depth: 16
      embed_dim: 768
      low_freqs: 12
      mlp_ratio: 4
      mlp_time_embed: true
      name: uvit_greyscale_moe
      num_classes: -1
      num_heads: 12
      qkv_bias: false
      tokens: 196
      use_moe: true
    _locked: false
    _type_safe: true
  optimizer: !!python/object:ml_collections.config_dict.config_dict.FrozenConfigDict
    _configdict: *id006
    _convert_dict: true
    _fields:
      betas: *id007
      lr: 0.0002
      name: adamw
      weight_decay: 0.03
    _locked: false
    _type_safe: true
  pred: noise_pred
  private: !!python/object:ml_collections.config_dict.config_dict.FrozenConfigDict
    _configdict: *id008
    _convert_dict: true
    _fields:
      accountant: prv
      dp_method: dpsgd
      max_grad_norm: 1.0
      noise_multiplier: 0.5
      secure_mode: false
      target_delta: 1.0e-05
      target_epsilon: 10
      use_dp: false
    _locked: false
    _type_safe: true
  sample: !!python/object:ml_collections.config_dict.config_dict.FrozenConfigDict
    _configdict: *id009
    _convert_dict: true
    _fields:
      algorithm: euler_maruyama_ode
      mini_batch_size: 500
      n_samples: 50000
      path: data/scratch/samples
      sample_steps: 100
      save_npz: ''
      save_start: 10000
    _locked: false
    _type_safe: true
  sample_dir: output_shift/echonet_dynamic_uncond_MoE6_greyscale_uvit_mid_4by4_Y_bound/samples
  seed: 1234
  train: !!python/object:ml_collections.config_dict.config_dict.FrozenConfigDict
    _configdict: *id010
    _convert_dict: true
    _fields:
      batch_size: 512
      eval_interval: 25000
      log_interval: 100
      mode: uncond
      n_steps: 500000
      save_interval: 25000
    _locked: false
    _type_safe: true
  workdir: output_shift/echonet_dynamic_uncond_MoE6_greyscale_uvit_mid_4by4_Y_bound
_locked: false
_type_safe: true
