!!python/object:ml_collections.config_dict.config_dict.FrozenConfigDict
_allow_dotted_keys: false
_configdict: !!python/object:ml_collections.config_dict.config_dict.ConfigDict
  _allow_dotted_keys: false
  _convert_dict: true
  _fields:
    ckpt_root: output_shift_fa/acdc_wholeheart_uncond_fa_ec_moe_greyscale_uvit_mid_4by4_l6r9_low16_Y_bound_nomlp/ckpts
    dataset: &id001 !!python/object:ml_collections.config_dict.config_dict.ConfigDict
      _allow_dotted_keys: false
      _convert_dict: true
      _fields:
        SNR_scale: 4.0
        Y_bound:
        - 502.5
        Y_entropy:
        - 5.883
        - 3.501
        - 3.575
        - 2.418
        - 2.75
        - 2.341
        - 1.479
        - 2.017
        - 2.044
        - 1.453
        - 1.316
        - 1.586
        - 1.365
        - 1.174
        - 1.108
        - 1.0
        Y_max:
        - 262.0
        - 112.375
        - 125.812
        - 49.0
        - 58.5
        - 46.5
        - 20.344
        - 32.906
        - 33.406
        - 19.953
        - 15.953
        - 22.0
        - 16.984
        - 12.812
        - 11.68
        - 7.461
        Y_mean:
        - -270.982
        - -0.725
        - 0.44
        - 0.107
        - 0.009
        - 0.154
        - -0.058
        - 0.0
        - -0.008
        - 0.019
        - 0.009
        - -0.012
        - 0.005
        - 0.002
        - 0.004
        - -0.002
        Y_min:
        - -502.5
        - -119.312
        - -122.375
        - -51.25
        - -58.906
        - -49.5
        - -20.703
        - -32.906
        - -33.094
        - -19.891
        - -15.891
        - -21.75
        - -16.969
        - -12.773
        - -11.648
        - -7.492
        Y_std:
        - 182.433
        - 32.822
        - 34.997
        - 14.001
        - 17.621
        - 13.189
        - 5.791
        - 9.609
        - 9.805
        - 5.653
        - 4.634
        - 6.503
        - 4.964
        - 3.796
        - 3.44
        - 2.178
        block_sz: 4
        dataset_type: wholeheart
        frequency_aware_tokens: true
        greyscale: true
        low_freqs: 16
        name: acdc_uncond
        num_fa_length: 8
        num_fa_repeats: 9
        num_fa_repeats_x: 3
        num_fa_repeats_y: 3
        path: data/scratch/datasets/ACDC/Unlabeled/Wholeheart
        resolution: 96
        reweight: true
        reweight_dim: -1
        temperature: 0.0
        tokens: 128
        tokenwise_normalization: Y_bound
      _locked: false
      _sort_keys: true
      _type_safe: true
    eval: &id002 !!python/object:ml_collections.config_dict.config_dict.ConfigDict
      _allow_dotted_keys: false
      _convert_dict: true
      _fields:
        cleanup_samples: true
        eval_start: 400000
        is_batch_size: 32
        lpips_batch_size: 32
        mini_batch_size: 500
        n_samples: 50000
        sample_steps: 100
      _locked: false
      _sort_keys: true
      _type_safe: true
    eval_dir: output/evaluation/FA_EC_l8r9_4by4_low16
    lr_scheduler: &id003 !!python/object:ml_collections.config_dict.config_dict.ConfigDict
      _allow_dotted_keys: false
      _convert_dict: true
      _fields:
        name: customized
        warmup_steps: 5000
      _locked: false
      _sort_keys: true
      _type_safe: true
    mixed_precision: 'no'
    name: acdc_wholeheart_uncond_uvit_FA_EC_MoE_greyscale_mid_4by4_low16_nomlp
    nnet: &id004 !!python/object:ml_collections.config_dict.config_dict.ConfigDict
      _allow_dotted_keys: false
      _convert_dict: true
      _fields:
        MoE: &id005 !!python/object:ml_collections.config_dict.config_dict.ConfigDict
          _allow_dotted_keys: false
          _convert_dict: true
          _fields:
            aux_loss_alpha: 0.0
            depth: 1
            noise_eps: 0.01
            num_experts: 4
            router: topk
            top_k: 2
            type: ecmoe
          _locked: false
          _sort_keys: true
          _type_safe: true
        depth: 16
        embed_dim: 768
        in_chans: 72
        low_freqs: 16
        mlp_ratio: 4
        mlp_time_embed: false
        name: uvit_greyscale_moe
        num_classes: -1
        num_heads: 12
        qkv_bias: false
        tokens: 128
        use_moe: true
      _locked: false
      _sort_keys: true
      _type_safe: true
    optimizer: &id006 !!python/object:ml_collections.config_dict.config_dict.ConfigDict
      _allow_dotted_keys: false
      _convert_dict: true
      _fields:
        betas: &id007 !!python/tuple
        - 0.99
        - 0.99
        lr: 0.0002
        name: adamw
        weight_decay: 0.03
      _locked: false
      _sort_keys: true
      _type_safe: true
    pred: noise_pred
    private: &id008 !!python/object:ml_collections.config_dict.config_dict.ConfigDict
      _allow_dotted_keys: false
      _convert_dict: true
      _fields:
        accountant: prv
        dp_method: dpsgd
        max_grad_norm: 1.0
        noise_multiplier: 0.5
        secure_mode: false
        target_delta: 1.0e-05
        target_epsilon: 10
        use_dp: false
      _locked: false
      _sort_keys: true
      _type_safe: true
    sample: &id009 !!python/object:ml_collections.config_dict.config_dict.ConfigDict
      _allow_dotted_keys: false
      _convert_dict: true
      _fields:
        algorithm: euler_maruyama_ode
        mini_batch_size: 500
        n_samples: 50000
        path: data/scratch/samples
        sample_steps: 100
        save_npz: ''
        save_start: 20000
      _locked: false
      _sort_keys: true
      _type_safe: true
    sample_dir: output_shift_fa/acdc_wholeheart_uncond_fa_ec_moe_greyscale_uvit_mid_4by4_l6r9_low16_Y_bound_nomlp/samples
    seed: 1234
    train: &id010 !!python/object:ml_collections.config_dict.config_dict.ConfigDict
      _allow_dotted_keys: false
      _convert_dict: true
      _fields:
        batch_size: 512
        eval_interval: 25000
        log_interval: 100
        mode: uncond
        n_steps: 500000
        save_interval: 25000
      _locked: false
      _sort_keys: true
      _type_safe: true
    workdir: output_shift_fa/acdc_wholeheart_uncond_fa_ec_moe_greyscale_uvit_mid_4by4_l6r9_low16_Y_bound_nomlp
  _locked: false
  _sort_keys: true
  _type_safe: true
_convert_dict: true
_fields:
  ckpt_root: output_shift_fa/acdc_wholeheart_uncond_fa_ec_moe_greyscale_uvit_mid_4by4_l6r9_low16_Y_bound_nomlp/ckpts
  dataset: !!python/object:ml_collections.config_dict.config_dict.FrozenConfigDict
    _allow_dotted_keys: false
    _configdict: *id001
    _convert_dict: true
    _fields:
      SNR_scale: 4.0
      Y_bound: !!python/tuple
      - 502.5
      Y_entropy: !!python/tuple
      - 5.883
      - 3.501
      - 3.575
      - 2.418
      - 2.75
      - 2.341
      - 1.479
      - 2.017
      - 2.044
      - 1.453
      - 1.316
      - 1.586
      - 1.365
      - 1.174
      - 1.108
      - 1.0
      Y_max: !!python/tuple
      - 262.0
      - 112.375
      - 125.812
      - 49.0
      - 58.5
      - 46.5
      - 20.344
      - 32.906
      - 33.406
      - 19.953
      - 15.953
      - 22.0
      - 16.984
      - 12.812
      - 11.68
      - 7.461
      Y_mean: !!python/tuple
      - -270.982
      - -0.725
      - 0.44
      - 0.107
      - 0.009
      - 0.154
      - -0.058
      - 0.0
      - -0.008
      - 0.019
      - 0.009
      - -0.012
      - 0.005
      - 0.002
      - 0.004
      - -0.002
      Y_min: !!python/tuple
      - -502.5
      - -119.312
      - -122.375
      - -51.25
      - -58.906
      - -49.5
      - -20.703
      - -32.906
      - -33.094
      - -19.891
      - -15.891
      - -21.75
      - -16.969
      - -12.773
      - -11.648
      - -7.492
      Y_std: !!python/tuple
      - 182.433
      - 32.822
      - 34.997
      - 14.001
      - 17.621
      - 13.189
      - 5.791
      - 9.609
      - 9.805
      - 5.653
      - 4.634
      - 6.503
      - 4.964
      - 3.796
      - 3.44
      - 2.178
      block_sz: 4
      dataset_type: wholeheart
      frequency_aware_tokens: true
      greyscale: true
      low_freqs: 16
      name: acdc_uncond
      num_fa_length: 8
      num_fa_repeats: 9
      num_fa_repeats_x: 3
      num_fa_repeats_y: 3
      path: data/scratch/datasets/ACDC/Unlabeled/Wholeheart
      resolution: 96
      reweight: true
      reweight_dim: -1
      temperature: 0.0
      tokens: 128
      tokenwise_normalization: Y_bound
    _locked: false
    _sort_keys: true
    _type_safe: true
  eval: !!python/object:ml_collections.config_dict.config_dict.FrozenConfigDict
    _allow_dotted_keys: false
    _configdict: *id002
    _convert_dict: true
    _fields:
      cleanup_samples: true
      eval_start: 400000
      is_batch_size: 32
      lpips_batch_size: 32
      mini_batch_size: 500
      n_samples: 50000
      sample_steps: 100
    _locked: false
    _sort_keys: true
    _type_safe: true
  eval_dir: output/evaluation/FA_EC_l8r9_4by4_low16
  lr_scheduler: !!python/object:ml_collections.config_dict.config_dict.FrozenConfigDict
    _allow_dotted_keys: false
    _configdict: *id003
    _convert_dict: true
    _fields:
      name: customized
      warmup_steps: 5000
    _locked: false
    _sort_keys: true
    _type_safe: true
  mixed_precision: 'no'
  name: acdc_wholeheart_uncond_uvit_FA_EC_MoE_greyscale_mid_4by4_low16_nomlp
  nnet: !!python/object:ml_collections.config_dict.config_dict.FrozenConfigDict
    _allow_dotted_keys: false
    _configdict: *id004
    _convert_dict: true
    _fields:
      MoE: !!python/object:ml_collections.config_dict.config_dict.FrozenConfigDict
        _allow_dotted_keys: false
        _configdict: *id005
        _convert_dict: true
        _fields:
          aux_loss_alpha: 0.0
          depth: 1
          noise_eps: 0.01
          num_experts: 4
          router: topk
          top_k: 2
          type: ecmoe
        _locked: false
        _sort_keys: true
        _type_safe: true
      depth: 16
      embed_dim: 768
      in_chans: 72
      low_freqs: 16
      mlp_ratio: 4
      mlp_time_embed: false
      name: uvit_greyscale_moe
      num_classes: -1
      num_heads: 12
      qkv_bias: false
      tokens: 128
      use_moe: true
    _locked: false
    _sort_keys: true
    _type_safe: true
  optimizer: !!python/object:ml_collections.config_dict.config_dict.FrozenConfigDict
    _allow_dotted_keys: false
    _configdict: *id006
    _convert_dict: true
    _fields:
      betas: *id007
      lr: 0.0002
      name: adamw
      weight_decay: 0.03
    _locked: false
    _sort_keys: true
    _type_safe: true
  pred: noise_pred
  private: !!python/object:ml_collections.config_dict.config_dict.FrozenConfigDict
    _allow_dotted_keys: false
    _configdict: *id008
    _convert_dict: true
    _fields:
      accountant: prv
      dp_method: dpsgd
      max_grad_norm: 1.0
      noise_multiplier: 0.5
      secure_mode: false
      target_delta: 1.0e-05
      target_epsilon: 10
      use_dp: false
    _locked: false
    _sort_keys: true
    _type_safe: true
  sample: !!python/object:ml_collections.config_dict.config_dict.FrozenConfigDict
    _allow_dotted_keys: false
    _configdict: *id009
    _convert_dict: true
    _fields:
      algorithm: euler_maruyama_ode
      mini_batch_size: 500
      n_samples: 50000
      path: data/scratch/samples
      sample_steps: 100
      save_npz: ''
      save_start: 20000
    _locked: false
    _sort_keys: true
    _type_safe: true
  sample_dir: output_shift_fa/acdc_wholeheart_uncond_fa_ec_moe_greyscale_uvit_mid_4by4_l6r9_low16_Y_bound_nomlp/samples
  seed: 1234
  train: !!python/object:ml_collections.config_dict.config_dict.FrozenConfigDict
    _allow_dotted_keys: false
    _configdict: *id010
    _convert_dict: true
    _fields:
      batch_size: 512
      eval_interval: 25000
      log_interval: 100
      mode: uncond
      n_steps: 500000
      save_interval: 25000
    _locked: false
    _sort_keys: true
    _type_safe: true
  workdir: output_shift_fa/acdc_wholeheart_uncond_fa_ec_moe_greyscale_uvit_mid_4by4_l6r9_low16_Y_bound_nomlp
_locked: false
_sort_keys: true
_type_safe: true
